/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCaseSlugRouteImport } from './routes/use-case.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCaseSlugRoute = UseCaseSlugRouteImport.update({
  id: '/use-case/$slug',
  path: '/use-case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/use-case/$slug': typeof UseCaseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/use-case/$slug': typeof UseCaseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/use-case/$slug': typeof UseCaseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/use-case/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/use-case/$slug'
  id: '__root__' | '/' | '/use-case/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UseCaseSlugRoute: typeof UseCaseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-case/$slug': {
      id: '/use-case/$slug'
      path: '/use-case/$slug'
      fullPath: '/use-case/$slug'
      preLoaderRoute: typeof UseCaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UseCaseSlugRoute: UseCaseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
